### ISSUE TITLE
Missing filter.json

### ISSUE THREAD

**Issue by Kryreth** [adi-panda/Kuebiko#44]
Error: File 'filter.json' not found.
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "C:\Users\ddkvi\miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\ddkvi\miniconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ddkvi\Downloads\Twitch AI\Kuebiko-main\Kuebiko-main\speaker_bot_based.py", line 52, in run
    asyncio.run(self.main())
  File "C:\Users\ddkvi\miniconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ddkvi\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ddkvi\miniconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ddkvi\Downloads\Twitch AI\Kuebiko-main\Kuebiko-main\speaker_bot_based.py", line 57, in main
    bad_words = read_json_file('filter.json')['blacklist']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by caesarakalaeii** [comment]
For now create a file called filter.json filled with 
```
{
    "blacklist": [
        "Bad Word"
    ],
    "ignored_users": [
        "Someone"
    ]
}
```

I'll push an update later that ensures all config files are created if not found
